### ISSUE TITLE
question about Mergepairs command

### ISSUE THREAD

**Issue by Alfredssss** [compmetagen/micca#11]
Hi,
When I use 

micca mergepairs -i *_R1*.fastq  -o Merged.fastq

it automatically recognize the R2 file? or I have to repeat the same command with R2  and then merge the two file sets?
thank you for the attention

**Comment by davidealbanese** [comment]
Dear @Alfredssss,
in this case the command recognizes  automatically the`R2` file but probably you mean:

```sh
micca mergepairs -i *_R1.fastq -o Merged.fastq
```

When only the option `-i` is specified (and not the option `-r/--reverse`) the reverse file name will be automatically constructed by replacing the string `_R1` in the forward file name with the corresponding `_R2` (default behaviour see options `-p/--pattern` and `-e/--repl`). You can also customize the replacing options, e.g. the command:

```sh
micca mergepairs -i *READ1.fastq -o merged.fastq -p READ1 -e READ2
```

will replace `READ1` with `READ2` searching in every file `*READ1.fastq`.

Moreover,  after the merging of the paired reads, different samples will be merged in a single file and sample names will be appended to the sequence identifier (e.g. `>SEQID;sample=SAMPLENAME`), as in`micca merge` and `micca split`. Sample names are defined as the leftmost part of the file name splitted by the first occurence of `_` (`-s/--sep` option).

**Comment by AndreaQ7** [comment]
Thank you a lot for your explaination!!!
