### ISSUE TITLE
problem with micca classify command

### ISSUE THREAD

**Issue by faizansaleem1992** [compmetagen/micca#13]
Hello,
I have been following the single end sequencing tutorial of micca for my 16s rrna samples and generated the otus.fasta and otu table files but I am stuck at micca classify ommand following is the command I am using and it gives the error,
micca classify -m rdp --rdp-gene 16srrna -i otus.fasta -o taxa.txt
Error: Error: RDPPATH environment variable is not set

I have rdp classifier sudo installed but I am unable to understand how to resolve this problem, Kindly help.

Best Regards,
Faizan Saleem

**Comment by davidealbanese** [comment]
Dear Faizan,
did you set the environment variable RDPPATH (http://micca.org/docs/latest/install.html#install-rdp-classifier-optional), e.g.:

```
$ export RDPPATH=/path-to-rdp-classifier/rdp_classifier_2.11/
```
