### ISSUE TITLE
Qiime2 to downstream analysis

### ISSUE THREAD

**Issue by bioinfonext** [compmetagen/micca#20]
Hi,

there is some error in micca installation on iMac, could you please advice how to fix it?
admins-imac-3:~ ygupta$ sudo pip install micca
Password:
The directory '/Users/ygupta/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/ygupta/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting micca
  Downloading https://files.pythonhosted.org/packages/8a/79/fc77ff9a93ad5053a32b2c83dd9eda606dcb342ae1a3f3587a59f266280e/micca-1.7.2.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 798kB/s 
Requirement already satisfied: numpy>=1.8.0 in ./miniconda2/lib/python2.7/site-packages (from micca)
Requirement already satisfied: scipy>=0.14.0 in ./miniconda2/lib/python2.7/site-packages (from micca)
Requirement already satisfied: matplotlib>=1.3.0 in ./miniconda2/lib/python2.7/site-packages (from micca)
Requirement already satisfied: pandas>=0.17.0 in ./miniconda2/lib/python2.7/site-packages (from micca)
Collecting biopython>=1.50 (from micca)
  Downloading https://files.pythonhosted.org/packages/55/fe/3c1ecd4fa3a4ac1c981ebf948a189d702b77aa842bf879ab460eaaa934ce/biopython-1.75-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 685kB/s 
Collecting cutadapt>=1.9 (from micca)
  Downloading https://files.pythonhosted.org/packages/fd/4d/3ac2947d36e2d56ce1513dc4a53d3a45e520d7ccfb43af9ba85408e44c69/cutadapt-1.18.tar.gz (342kB)
    100% |████████████████████████████████| 348kB 4.8MB/s 
Requirement already satisfied: biom-format>=1.3.1 in ./miniconda2/lib/python2.7/site-packages (from micca)
Requirement already satisfied: six>=1.10 in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Requirement already satisfied: python-dateutil>=2.0 in ./miniconda2/lib/python2.7/site-packages/python_dateutil-2.3-py2.7.egg (from matplotlib>=1.3.0->micca)
Requirement already satisfied: backports.functools_lru_cache in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Requirement already satisfied: subprocess32 in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Requirement already satisfied: pytz in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Requirement already satisfied: cycler>=0.10 in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./miniconda2/lib/python2.7/site-packages (from matplotlib>=1.3.0->micca)
Collecting xopen>=0.3.2 (from cutadapt>=1.9->micca)
  Downloading https://files.pythonhosted.org/packages/73/e9/bc35fd93cb6af3a011e44463db468914448825aa659f7636e836b8488b03/xopen-0.8.4-py2.py3-none-any.whl
Requirement already satisfied: click in ./miniconda2/lib/python2.7/site-packages (from biom-format>=1.3.1->micca)
Requirement already satisfied: future>=0.16.0 in ./miniconda2/lib/python2.7/site-packages (from biom-format>=1.3.1->micca)
Requirement already satisfied: pyqi in ./miniconda2/lib/python2.7/site-packages (from biom-format>=1.3.1->micca)
Collecting bz2file; python_version == "2.7" (from xopen>=0.3.2->cutadapt>=1.9->micca)
  Downloading https://files.pythonhosted.org/packages/61/39/122222b5e85cd41c391b68a99ee296584b2a2d1d233e7ee32b4532384f2d/bz2file-0.98.tar.gz
Installing collected packages: biopython, bz2file, xopen, cutadapt, micca
  Running setup.py install for bz2file ... done
  Running setup.py install for cutadapt ... done
  Running setup.py install for micca ... error
    Complete output from command /Users/ygupta/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-rZUyQD/micca/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-foXnJD-record/install-record.txt --single-version-externally-managed --compile:
    Building VSEARCH...
    ./autogen.sh: line 2: autoreconf: command not found
    
    ----------------------------------------
**Command "/Users/ygupta/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-rZUyQD/micca/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-foXnJD-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-rZUyQD/micca/**
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
thanks
Yogesh

**Comment by davidealbanese** [comment]
Hi,
the downstream tutorial requires [Paired-end sequencing tutorial ](https://micca.readthedocs.io/en/latest/pairedend_97.html) to be done.

Cheers,
Davide
