### ISSUE TITLE
core_set?

### ISSUE THREAD

**Issue by Phylloxera** [compmetagen/micca#23]
Hello,

Great tool, I recommend it for everyone here at our lab! Hadn't run myself in some time but was helping some other folks out and discovered that this link from the latest documentation no longer works.
`wget ftp://ftp.fmach.it/metagenomics/micca/dbs/core_set.tar.gz`

> No such directory ‘metagenomics/micca/dbs’.

Also found this [qiime issue](https://github.com/biocore/qiime/issues/1770) from 2014.

Thoughts?

**Comment by davidealbanese** [comment]
Fixed!

**Comment by Phylloxera** [comment]
Hi @davidealbanese,

A user at my site says this is down again. Can you check?

Thanks

**Comment by davidealbanese** [comment]
Related to #29
