### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by Alenap26** [compmetagen/micca#24]
Hello, when I do: python setup.py install,
I obtain the following error:
`Building VSEARCH...
Building MUSCLE...

Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    _build_muscle()
  File "setup.py", line 71, in _build_muscle
    _system_call(["make"])
  File "setup.py", line 44, in _system_call
    sys.stderr.write(proc_stderr)
TypeError: write() argument must be str, not bytes`

I'm working on Python 3.8.1, Can you help me ?
Thanks for your time.

**Comment by davidealbanese** [comment]
Dear @Alenap26,

for the moment, only Python 2.7 is supported. I'm working on micca2 (for Python 3.5+) and I think that it will be released in March. Meanwhile you can use the Docker image (https://hub.docker.com/r/compmetagen/micca/).
