### ISSUE TITLE
Merge paired-end sequences in micca

### ISSUE THREAD

**Issue by altinok68** [compmetagen/micca#25]
Hello,
I am using micca, my file name is P1_1.fq and P1_2.fq. When I used "micca mergepairs -i fastq/P1_1.fastq -o merged.fastq -l 100 -d 30" command,  "P1_1.fastq: unable to find pattern '_R1', SKIP"  error come up. I changed the file name as P1_R1.fq and P1_R2.fq and same error occurred.
Can you help me how can I solve the problem.
Thanks in advance
Best wishes

**Comment by davidealbanese** [comment]
@altinok68, if your file names are `P1_R1.fq` and `P1_R2.fq` you should run:

```sh
micca mergepairs -i fastq/P1_R1.fq -o merged.fastq -l 100 -d 30
```
note that the extension of `P1_R1` is `fq` and not `fastq`.

Cheers,
Davide

**Comment by altinok68** [comment]
Dear Davide,
Thank you for your information
best wishes,
-- 
ilhan Altinok
Karadeniz Technical University
Faculty of Marine Sciences
61530 Surmene, Trabzon, TURKEY
Ph:   90 462 377 8083
Fax:  90 462 752 2158
Email:ialtinok@ktu.edu.tr <ialtinok@ktu.edu.tr>
http://aves.ktu.edu.tr/ialtinok/
<http://enformatik.ktu.edu.tr/eakademik/3465/>
https://www.researchgate.net/profile/Ilhan_Altinok
*https://orcid.org/0000-0003-3475-521X
<https://orcid.org/0000-0003-3475-521X>*
<http://enformatik.ktu.edu.tr/eakademik/3465/>

**Comment by altinok68** [comment]
Dear David,



I have fastq files (IK0-5_1.fastq and IK0-5_2.fastq) and run the following
command



(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i
fastq/IK0-5_1.fastq -o merged.fastq



get the following error message;

Error: [Errno 2] No such file or directory: 'fastq/IK0-5_1.fastq'



I renamed the fastq file as IK0-5_R1.fastq and IK0-5_R2.fastq and run the
following command



(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i fastq/*R1.fastq
-o merged.fastq



get the following error message;



Error: [Errno 2] No such file or directory: 'fastq/*R1.fastq'



I tried different command and get the same error messages



(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i fastq/*.fastq -o
merged.fastq

Error: [Errno 2] No such file or directory: 'fastq/*.fastq'

(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i fastq/*_R1.fastq
-o merged.fastq

Error: [Errno 2] No such file or directory: 'fastq/*_R1.fastq'

(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i fastq/*_1.fastq
-o merged.fastq

Error: [Errno 2] No such file or directory: 'fastq/*_1.fastq'



Can you help me about this problem?



Best wishes
-- 
ilhan Altinok
Karadeniz Technical University
Faculty of Marine Sciences
61530 Surmene, Trabzon, TURKEY
Ph:   90 462 377 8083
Fax:  90 462 752 2158
Email:ialtinok@ktu.edu.tr <ialtinok@ktu.edu.tr>
http://aves.ktu.edu.tr/ialtinok/
<http://enformatik.ktu.edu.tr/eakademik/3465/>
https://www.researchgate.net/profile/Ilhan_Altinok
*https://orcid.org/0000-0003-3475-521X
<https://orcid.org/0000-0003-3475-521X>*
<http://enformatik.ktu.edu.tr/eakademik/3465/>

**Comment by davidealbanese** [comment]
Dear @altinok68,
given two files `IK0-5_1.fastq` and `IK0-5_2.fastq` note that the direction of the sequences are defined by the strings `_1` and  `_2` while the sample ID is  `IK0-5`. Therefore, you would run the command:

```sh
micca mergepairs -i fastq/IK0-5_1.fastq -o merged.fastq -p "_1" -e "_2"
```

(default values are `_R1` and `_R2` for `-p` and `-e`, respectively).

See the latest note in https://micca.readthedocs.io/en/latest/pairedend_97.html#merge-paired-end-sequences and the page https://micca.readthedocs.io/en/latest/commands/mergepairs.html

**Comment by altinok68** [comment]
Dear David,
Thank you for your prompt reply.
I entered the script that you send me but I get the following error.

*(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca merge -i
fastq/IK0-5_1.fastq -o merged.fastq -p "_1" -e "_2"*



*usage: micca merge [-h] -i FILE [FILE ...] -o FILE [-s SEP] [-f
{fastq,fasta}]*

*micca merge: error: unrecognized arguments: -p _1 -e _2*

*best wishes,*

*ilhan*

**Comment by davidealbanese** [comment]
`micca mergepairs` and not `micca merge`, I apologize for the error.

**Comment by altinok68** [comment]
Dear David,
This time following error occurred.

*(base) ilhan@ilhan-VirtualBox:~/metagenome$ micca mergepairs -i
fastq/IK0-5_1.fastq -o merged.fastq -p _1 -e _2*


*IK0-5_2.fastq: file does not exist or is not a regular file, SKIP*
-- 
Prof. Dr. ilhan Altinok
Karadeniz Technical University
Faculty of Marine Sciences
61530 Surmene, Trabzon, TURKEY
Ph:   90 462 377 8083
Fax:  90 462 752 2158
Email:ialtinok@ktu.edu.tr <ialtinok@ktu.edu.tr>
http://aves.ktu.edu.tr/ialtinok/
<http://enformatik.ktu.edu.tr/eakademik/3465/>
https://www.researchgate.net/profile/Ilhan_Altinok
*https://orcid.org/0000-0003-3475-521X
<https://orcid.org/0000-0003-3475-521X>*
<http://enformatik.ktu.edu.tr/eakademik/3465/>

**Comment by davidealbanese** [comment]
Dear @altinok68,

do you have the file `IK0-5_2.fastq` in the directory `~/metagenome/fastq`?

**Comment by altinok68** [comment]
yes I have

*Original files were *.fastq.gz, they were gunzipped in the termimal*

**Comment by davidealbanese** [comment]
Please post the output of `ls -l ~/metagenome/fastq`, thanks

**Comment by altinok68** [comment]
(base) ilhan@ilhan-VirtualBox:~$ ls -l ~/metagenome

total 410812

drwxr-xr-x 2 ilhan ilhan     4096 Nis 19 10:04 fastq-join_joined

-rw-r--r-- 1 ilhan ilhan 37962135 Nis 18 11:53 IK0-5M_1

-rwxrwx--- 1 ilhan ilhan 68961368 Nis 16 08:54 IK0-5M_1.fastq

-rw-r--r-- 1 ilhan ilhan 37939759 Nis 18 11:54 IK0-5M_2

-rwxrwx--- 1 ilhan ilhan 68961368 Nis 16 08:53 IK0-5M_2.fastq

-rw-r--r-- 1 ilhan ilhan        0 Nis 20 16:32 merged.fastq

**Comment by davidealbanese** [comment]
Dear @altinok68,
FASTQ files are not in a `fastq` folder.
It seems to me that you don't have the proper background to run a command line tool like micca, so I suggest you to get help from a bioinformatician.

Regards,
Davide

**Comment by altinok68** [comment]
Dear David,

This is last question.

After reinstalling micca, I download garda file to play with the commands
and get the following error.



(base) ilhan@ilhan-VirtualBox:~$ cd garda

(base) ilhan@ilhan-VirtualBox:~/garda$ micca mergepairs -i
fastq/*_R1*.fastq -o merged.fastq -l 100 -d 30

Error: a bytes-like object is required, not 'str'
ilhan
