### ISSUE TITLE
Error: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by arnemalzhan** [compmetagen/micca#26]
Hello,
I just installed micca on my ubuntu 18 installed in virtual box. I also downloaded the garda file to make an exercise. After entering following command, an error occurred. 
(base) arne@arne-:~/garda$ micca mergepairs -i fastq/*_R1*.fastq -o merged.fastq -l 100 -d 30
Error: a bytes-like object is required, not 'str'
Can you help me to solve the problem?
Best wishes,
Arne

**Comment by davidealbanese** [comment]
Related to #24.
