### ISSUE TITLE
Running setup.py install for micca ... error

### ISSUE THREAD

**Issue by arnemalzhan** [compmetagen/micca#27]
Hi,
During the instillation of micca, following error message appeared.
Can you help me how to solve it.

Collecting micca

Downloading https://files.pythonhosted.org/packages/8a/79/fc77ff9a93ad5053a32b2c83dd9eda606dcb342ae1a3f3587a59f266280e/micca-1.7.2.tar.gz (2.1MB)

100% |████████████████████████████████| 2.1MB 372kB/s

Requirement already satisfied: numpy>=1.8.0 in /usr/lib/python3/dist-packages (from micca)

Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: matplotlib>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: biopython>=1.50 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: cutadapt>=1.9 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: biom-format>=1.3.1 in /usr/local/lib/python3.6/dist-packages (from micca)

Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.0->micca)

Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.0->micca)

Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.0->micca)

Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from matplotlib>=1.3.0->micca)

Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas>=0.17.0->micca)

Requirement already satisfied: dnaio~=0.4.2 in /usr/local/lib/python3.6/dist-packages (from cutadapt>=1.9->micca)

Requirement already satisfied: xopen~=0.8.4 in /usr/local/lib/python3.6/dist-packages (from cutadapt>=1.9->micca)

Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from biom-format>=1.3.1->micca)

Requirement already satisfied: cython in ./.local/lib/python3.6/site-packages (from biom-format>=1.3.1->micca)

Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.6/dist-packages (from biom-format>=1.3.1->micca)

Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from biom-format>=1.3.1->micca)

Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from biom-format>=1.3.1->micca)

Installing collected packages: micca

Running setup.py install for micca ... error

Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xazzw28s/micca/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6fh62fud-record/install-record.txt --single-version-externally-managed --compile:

Building VSEARCH...

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "/tmp/pip-build-xazzw28s/micca/setup.py", line 119, in <module>

_build_vsearch()

File "/tmp/pip-build-xazzw28s/micca/setup.py", line 54, in _build_vsearch

_system_call(["./autogen.sh"])

File "/tmp/pip-build-xazzw28s/micca/setup.py", line 44, in _system_call

sys.stderr.write(proc_stderr)

TypeError: write() argument must be str, not bytes

----------------------------------------

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xazzw28s/micca/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6fh62fud-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xazzw28s/micca/

**Comment by davidealbanese** [comment]
Related to #24.
