### ISSUE TITLE
Error when connecting to ftp.fmach.it link

### ISSUE THREAD

**Issue by Tutter1998** [compmetagen/micca#29]
Using MICCA to process 16S data and when I go to generate a phylogenetic tree I discovered that the following link from the latest documentation no longer works:
wget ftp://ftp.fmach.it/metagenomics/micca/dbs/core_set.tar.gz

I get the following error:
Connecting to ftp.fmach.it (ftp.fmach.it)|77.72.197.176|:21... failed: Connection refused.

Thoughts?

**Comment by davidealbanese** [comment]
Dear @Tutter1998,
`wget ftp://ftp.fmach.it/metagenomics/micca/dbs/core_set.tar.gz` works for me now
