### ISSUE TITLE
Resource Temporarily Unavailable; Connection Timed Out; Connection Refused for core set from ftp site

### ISSUE THREAD

**Issue by Phylloxera** [compmetagen/micca#30]
Hi @davidealbanese ,

Issue #29 seems to be not fully resolved. I tried `wget ftp://ftp.fmach.it/metagenomics/micca/dbs/core_set.tar.gz` from a couple of different machines this morning. The connection refused issue may be a separate gov firewall issue on our end, but I got 'Resource Temporarily Unavailable' and 'Connection Timed Out' when attempting from computers that should not have been subject to the firewall.

**Comment by davidealbanese** [comment]
The issue should be definitively fixed now.
Anyway, I recommend making a **local copy** on your server.
