### ISSUE TITLE
Micca assumes DataFrames are saved with the index on the first column

### ISSUE THREAD

**Issue by glucksfall** [compmetagen/micca#32]
Hello,

I found out that micca reads csv files from DataFrames with the index on the first column: `table = pd.read_csv(input_fn, sep='\t', index_col=0)` (line 12, micca/table.py file).

If the user isn't aware (as me), saving a csv without the index will result in the drop of the first sample when calculating table summaries and plotting the rarefaction curve.

Best regards.

**Comment by davidealbanese** [comment]
Dear @glucksfall,
see https://micca.readthedocs.io/en/latest/formats.html#otu-sv-tables-and-taxonomy-tables.
