### ISSUE TITLE
issue about installing micca

### ISSUE THREAD

**Issue by weibokong27** [compmetagen/micca#34]
Hi:

Is micca no longer maintained/updated? I keep getting the error installing on Linux:

sudo apt-get update
sudo apt-get install build-essential python-numpy gcc gfortran python-dev libblas-dev liblapack-dev cython pkg-config libfreetype6 libfreetype6-dev libpng-dev
pip install --upgrade pip
pip install 'setuptools >=14.0'
pip install micca

So I try to install micca from source, but it also does work:

sudo pip install 'scipy >=0.13.0' 'pandas >=0.17.0' 'matplotlib >=1.3.0' 'biopython >= 1.50' 'cutadapt >=1.9' 'biom-format >=1.3.1'
tar -zxvf micca-1.7.2.tar.gz
sudo python setup.py install
error: Setup script exited with Python 2.7 is no longer supported

Then, I build a python 2.7 environment:
conda create -n envpython27 python=2.7 -y
conda activate envpython27

Then perform the above installation, still error.

**Comment by davidealbanese** [comment]
Dear @weibokong27,
you can use the Docker image (https://hub.docker.com/r/compmetagen/micca/).
