### ISSUE TITLE
Regarding setup.py installation

### ISSUE THREAD

**Issue by Engy922** [compmetagen/micca#35]
I am trying to install micca from source code using 
sudo python setup.py install

But gives me at the end error entitled
File "/tmp/easy_install-Ir3wOg/scipy-1.10.1/setup.py", line 27, in <module>
    'Environment :: Console',
ImportError: No module named tools.version_utils
(That is the end of the error) and I searched for this module to install with no results
Is there a solution ?

**Comment by davidealbanese** [comment]
Dear @Engy922, I recommend you to use the Docker image (see https://hub.docker.com/r/compmetagen/micca/).
