### ISSUE TITLE
'Filter' returns only FASTA, not FASTQ

### ISSUE THREAD

**Issue by vmikk** [compmetagen/micca#7]
Hello!
I tried to filter sequences according to the maximum allowed expected error rate and specified the output file to be FASTQ. However, the result appears to be FASTA.
I used the following command:

```
micca filter \
 -i tst.fastq \
 -o tst_filter.fastq \
 -e 1 -m 200
```

micca v.1.6.0, installed using Docker in Ubuntu.
Did I miss something, or it is a bug?
Thank you for your help!
Vladimir

**Comment by davidealbanese** [comment]
Dear @vmikk,
you need to add the parameter `-f fastq`. 

Sorry for the late reply.
Davide
