### ISSUE TITLE
Missing sampledata.txt for the paired-end tutorial data

### ISSUE THREAD

**Issue by davidealbanese** [compmetagen/micca#8]
Missing sampledata.txt for the paired-end tutorial data.

**Comment by Phylloxera** [comment]
I'd definitely like to see the format for this. I've been unable to introduce any metadata into the biom file... only the ID. All other metadata columns resolve with "NA" values in the output.

**Comment by davidealbanese** [comment]
Dear @Phylloxera,
you can find the description of the sample data file here http://micca.org/docs/latest/formats.html#sample-data, and an example in the single-end tutorial file: ftp://ftp.fmach.it/metagenomics/micca/examples/mwanihana.tar.gz
